import Head from 'next/head';
import {BsFillMoonStarsFill} from 'react-icons/bs';
import {AiFillTwitterCircle, AiFillLinkedin} from "react-icons/ai" ;
import Image from 'next/image';
import deved from 'public/propic.jpeg';
import code from 'public/code.png';
import {useState} from 'react';
import { open } from 'fs';

export default function Home() {
  const [darkMode,setDarkMode] = useState(true);
  return (
    <div className={darkMode?"dark":""}>
      <Head>
        <title>Vittorio Compagno Portfolio Website</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=' bg-slate-100 px-10 font-mono md:px-20 lg:px-40 dark:bg-slate-900 '>
        <section className='min-h-screen'>
          <nav className='py-10 mb-12  flex justify-between'>
            <h1 className=' text-black dark:text-teal-400 text-sm'>Cats are superior</h1>
            <ul className = 'flex flex-row sm:flex-row items-center w-full sm:w-auto sm:text-sm'>
            
              <li>
                <a className=' bg-gradient-to-r from-cyan-600 to-teal-500  text-white px-4 py-2 border-none rounded-md ml-4 ' href="###">Resume</a>
              </li>
              <li className = 'border-none rounded-md ml-8 bg-gradient-to-r from-cyan-600 to-teal-500 px-4 py-2 text-xl'>
                  <BsFillMoonStarsFill onClick={()=>setDarkMode(!darkMode)} className='cursor-pointer text-white'/>
              </li>
            </ul>
          </nav>
          <div className=' relative mx-auto  bg-gradient-to-b from-teal-500 rounded-full w-60 h-60 mt-10 mb-7 overflow-hidden'>
            <Image src={deved} alt= "That's me" fill objectFit='cover' />
          </div>
          <div className= 'text-black dark:text-white text-center p-8 mx-auto max-w-2xl'>
            <h1 className=' text-5xl text-teal-700 dark:text-teal-400 font-medium'>Vittorio Compagno</h1>
            <h3 className=' text-2xl pt-5 text-teal-700 dark:text-teal-400'>Developer</h3>
            <div className='justify-center text-medium py-4 leading-6.5'>  
              <p>
              Welcome to Vittorio Compagno's <b>portfolio website</b>: a vibrant hub where creativity meets code. I'm a software developer with a passion for crafting elegant solutions to complex problems.
              </p>
              <p>
              <br /> Browse through my projects that demonstrate my expertise in cutting-edge technologies and commitment to delivering exceptional user experiences. <b> Let's collaborate and shape the future of technology, one line of code at a time! </b>
              </p>
            </div>
          </div>
          <div className=' text-4xl flex justify-center gap-16 p-10 py-1 text-gray-400 dark:text-teal-400'>
              <a href="https://www.twitter.com/comradvittorio" target='_blank' >
                <AiFillTwitterCircle className='cursor-pointer'/>
              </a>
              <a href="https://www.linkedin.com/in/vittorio-compagno" target='_blank'>
                <AiFillLinkedin className='cursor-pointer'/>
              </a>
            </div>
        </section>
        <section className='min-h-screen flex items-center justify-center'>
          <div className='grid justify-items-center lg:flex gap-10 my-10'>
            <div className='max-w-lg'>
               <div className='text-center shadow-2xl p-10 rounded-xl  bg-slate-200 text-black dark:text-white dark:bg-slate-800'>
               {  /*
                <div className='flex justify-center'>
                < Image src={code}  height={100} width={100} alt = 'miao'/>
                </div>
                */
              } 
                 <h3 className='pt-2 pb-2 text-2xl font-medium text-left  text-teal-700 dark:text-teal-400'> ETL Developer </h3>
                 <h2 className='text-lg text-left mb-3 dark:text-gray-200 text-gray-500'> GFT Technologies - June 2022 </h2>
                 <p className='text-left leading-6.5'>
                 As an ETL Developer at GFT Technologies, my role revolves around managing data to empower our company's decision-making process. Utilizing <b> Oracle SQL, Bash, Git, and Datastage </b>, I focus on the extraction, transformation, and loading of complex data sets. By ensuring data is clean and well-integrated, I provide a solid foundation for our team to build upon. My expertise in these technologies, combined with a dedication to professionalism and accuracy, allows me to contribute significantly to GFT Technologies' data-driven success.                         </p>
               </div>
            </div>
            <div className='max-w-lg'>
               <div className='text-center shadow-2xl p-10 rounded-xl bg-slate-200 text-black dark:text-white dark:bg-slate-800'>
               {  /*
                <div className='flex justify-center'>
                < Image src={code}  height={100} width={100} alt = 'miao'/>
                </div>
                */
              } 
                 <h3 className='pt-2 pb-2 text-2xl font-medium text-left  text-teal-700 dark:text-teal-400'> ETL Developer </h3>
                 <h2 className='text-lg text-left mb-3 dark:text-gray-200 text-gray-500'> GFT Technologies - June 2022 </h2>
                 <p className='text-left leading-6.5'>
                  aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa</p>
              </div>
            </div>
          </div>
        </section>
      </main>
    </div>
  )
}
